# CREATE DATABASE
CREATE DATABASE IF NOT EXISTS DIS_MONITORING;

# DROP USER 'dis_user';
CREATE USER 'dis_user'@'%' IDENTIFIED BY 'dis_password';

GRANT CREATE,SELECT,INSERT,UPDATE,DELETE,EXECUTE,ALTER,DROP ON DIS_MONITORING.* TO 'dis_user'@'%';

# SWITCH TO DATABASE
USE DIS_MONITORING;

# CREATE IOS DEVICES REGISTER TABLE
# DROP TABLE DIS_MONITORING.TBL_IOS_DEVICES_REGISTER;
CREATE TABLE IF NOT EXISTS DIS_MONITORING.TBL_IOS_DEVICES_REGISTER (
	DEVICE_ID VARCHAR(200) NOT NULL
	,DEVICE_NAME VARCHAR(200)
	,DEVICE_TOKEN VARCHAR(200)
	,NETWORK_NAME VARCHAR(200)
	,LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL
	,EX_COL1 VARCHAR(200)
	,EX_COL2 VARCHAR(200)
    ,CNTR BIGINT AUTO_INCREMENT
	,PRIMARY KEY (CNTR)
);

# CREATE IOS DEVICES HISTORY TABLE
# DROP TABLE DIS_MONITORING.TBL_IOS_DEVICES_HISTORY;
CREATE TABLE IF NOT EXISTS DIS_MONITORING.TBL_IOS_DEVICES_HISTORY (
	DEVICE_ID VARCHAR(200) NOT NULL
	,DEVICE_NAME VARCHAR(200)
	,NETWORK_NAME VARCHAR(200)
	# NOTE: For first release, CHECK_TYPE will be hard coded to HEART-BEAT
	,CHECK_TYPE VARCHAR(50)
    # NOTE: LAST_STATUS: OK, WARNING & CRITICAL
    ,LAST_STATUS VARCHAR(20)
	,STATUS_COUNT INT(8)
	,LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL
	,EX_COL1 VARCHAR(200)
	,EX_COL2 VARCHAR(200)
    ,CNTR BIGINT AUTO_INCREMENT
	,PRIMARY KEY (CNTR)
);

# CREATE DIS DEVICES REGISTER TABLE
# DROP TABLE DIS_MONITORING.TBL_VBS_DEVICES_REGISTER;
CREATE TABLE IF NOT EXISTS DIS_MONITORING.TBL_VBS_DEVICES_REGISTER (
	DEVICE_ID VARCHAR(200) NOT NULL
	,DEVICE_NAME VARCHAR(200)
	,DISPLAY_STATUS TINYINT
	,LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL
	,EX_COL1 VARCHAR(200)
	,EX_COL2 VARCHAR(200)
    ,CNTR BIGINT AUTO_INCREMENT
	,PRIMARY KEY (CNTR)
);

# CREATE DIS DEVICES HISTORY TABLE
# DROP TABLE DIS_MONITORING.TBL_VBS_DEVICES_HISTORY;
CREATE TABLE IF NOT EXISTS DIS_MONITORING.TBL_VBS_DEVICES_HISTORY (
	DEVICE_ID VARCHAR(200) NOT NULL
	,DEVICE_NAME VARCHAR(200)
	# NOTE: For first release, CHECK_TYPE will be hard coded to CONTENT-VERIFICATION
	,CHECK_TYPE VARCHAR(50)
    # NOTE: LAST_STATUS: OK, WARNING & CRITICAL
    ,LAST_STATUS VARCHAR(20)
	,STATUS_COUNT INT(8)
	,DISPLAY_STATUS TINYINT
	,LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL
	,EX_COL1 VARCHAR(200)
	,EX_COL2 VARCHAR(200)
    ,CNTR BIGINT AUTO_INCREMENT
	,PRIMARY KEY (CNTR)
);

# CREATE CONFIGURATION TABLE
# DROP TABLE DIS_MONITORING.TBL_CONFIG;
CREATE TABLE IF NOT EXISTS DIS_MONITORING.TBL_CONFIG (
	AGENT_TYPE VARCHAR(200) NOT NULL
	,CFG_KEY VARCHAR(200)
	,CFG_VAL VARCHAR(200)
	,LAST_UPDATE_TIMESTAMP TIMESTAMP NOT NULL
	,PRIMARY KEY (AGENT_TYPE, CFG_KEY, LAST_UPDATE_TIMESTAMP) 
);

# --------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','NRDP_TIMEOUT','2000',sysdate());
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','POLLER_TIME','600000',sysdate());
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','THRESHOLD_DURATION','900000',sysdate());
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','CREATOR','Sachin Jain + Mike Z',sysdate());
# --------------------------------------------------------------------------------------------------------------------------------------------
# Value for the Nagios NRDP Token
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','NRDP_TOKEN','spi-testing',sysdate());
# Value for the Nagios Mediator Web Service Port
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','JETTY_PORT','23000',sysdate());
# Value for the Nagios NRDP URL
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('MED','NRDP_URL','http://esu4v388/nrdp/',sysdate());
# Value for the Nagios iOS Monitor WARNING message limit
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('IOS','IOS_WARN_LIMIT','3',sysdate());
# Value for the Nagios VBS Content Verification Service Name
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('IOS','NRDP_SERVICE_IOS','DIS-iOS-Montior-Svc',sysdate());
# Value for the Nagios VBS Content Verification WARNING message limit
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('VBS','VBS_WARN_LIMIT','3',sysdate());
# Value for the Nagios iOS Monitor Service Name
INSERT INTO DIS_MONITORING.TBL_CONFIG (AGENT_TYPE,CFG_KEY,CFG_VAL,LAST_UPDATE_TIMESTAMP) VALUES ('VBS','NRDP_SERVICE_VBS','DIS-VBS-CV-Svc',sysdate());
# --------------------------------------------------------------------------------------------------------------------------------------------
COMMIT;
# --------------------------------------------------------------------------------------------------------------------------------------------
